name: release

on:
  push:
    tags:
      - docker-*

env:
  windows_version: 10

jobs:

  build:
    runs-on: windows-2019
    steps:

      - uses: actions/checkout@v1

      - name: Get current release tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/docker-}" >> $env:GITHUB_OUTPUT

      - name: Build docker image abenevaut/msys2
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag abenevaut/msys2:${{ steps.branch-name.outputs.SOURCE_TAG }}-windows${{ env.windows_version }} --cache-from abenevaut/msys2:latest-windows${{ env.windows_version }}
          docker tag abenevaut/msys2:${{ steps.branch-name.outputs.SOURCE_TAG }}-windows${{ env.windows_version }} abenevaut/msys2:latest-windows${{ env.windows_version }}
          docker push --all-tags abenevaut/msys2
